/**
 * Bundle the local pipeline.
 *
 * The pipeline imports the same adapter and analysis code the Worker uses, so
 * there is exactly one implementation of the maths. esbuild resolves the
 * extensionless TypeScript imports that plain Node cannot, and emits a single
 * .mjs that a scheduler can run with no build step and no dependencies.
 */
import { build } from 'esbuild';
import { existsSync, readFileSync } from 'node:fs';

// Load local/.env before anything reads process.env, so `npm run pipeline`
// behaves the same as the scheduled task.
export function loadEnv(path = 'local/.env') {
  if (!existsSync(path)) return;
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const i = t.indexOf('=');
    if (i < 0) continue;
    const k = t.slice(0, i).trim();
    const v = t.slice(i + 1).trim().replace(/^["']|["']$/g, '');
    if (!(k in process.env)) process.env[k] = v;
  }
}

// One config for every local entry point, so the manual-data CLI is bundled
// exactly the way the pipeline is: same target, same env loader, same
// externals.
const common = {
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  // These packages use Node/CommonJS internals such as `stream`. Keeping
  // them external avoids esbuild's ESM wrapper turning their require calls
  // into unsupported dynamic imports.
  external: ['exceljs', 'pdf-parse'],
  // Node has fetch, AbortSignal.timeout and crypto built in; nothing external
  // is needed at run time.
  banner: {
    js:
      '// Generated by local/build.mjs. Do not edit.\n' +
      "import { existsSync as __ex, readFileSync as __rf } from 'node:fs';\n" +
      'if (__ex("local/.env")) { for (const l of __rf("local/.env","utf8").split("\\n")) { const t=l.trim(); if(!t||t.startsWith("#"))continue; const i=t.indexOf("="); if(i<0)continue; const k=t.slice(0,i).trim(); const v=t.slice(i+1).trim().replace(/^["\']|["\']$/g,""); if(!(k in process.env)) process.env[k]=v; } }\n',
  },
};

const entries = [
  { entryPoints: ['local/pipeline.ts'], outfile: 'local/dist/pipeline.mjs' },
  { entryPoints: ['local/manual-data.ts'], outfile: 'local/dist/manual-data.mjs' },
];

for (const entry of entries) {
  await build({ ...common, ...entry });
  console.log(`Built ${entry.outfile}`);
}
