<#
    Register the Tereflow pipeline as a Windows scheduled task.

    Runs every Friday at 21:00 GMT. The task is created in local time with the
    offset worked out for you, because Task Scheduler has no notion of UTC.

    Run this from an elevated PowerShell prompt, once:

        powershell -ExecutionPolicy Bypass -File local\schedule-windows.ps1

    To remove it:

        Unregister-ScheduledTask -TaskName Tereflow-Pipeline -Confirm:$false
#>

param(
    [string]$TaskName = 'Tereflow-Pipeline',
    # 21:00 GMT. Change only if you want a different publication time.
    [int]$UtcHour = 21,
    [string]$DayOfWeek = 'Friday'
)

$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot
$script = Join-Path $repo 'local\dist\pipeline.mjs'

if (-not (Test-Path $script)) {
    Write-Host "Pipeline is not built yet. Run this first:" -ForegroundColor Yellow
    Write-Host "    cd `"$repo`"" -ForegroundColor Yellow
    Write-Host "    npm run pipeline:build" -ForegroundColor Yellow
    exit 1
}

if (-not (Test-Path (Join-Path $repo 'local\.env'))) {
    Write-Host "local\.env is missing. Copy local\.env.example and fill it in." -ForegroundColor Yellow
    exit 1
}

$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node) { throw 'node is not on PATH.' }

# Task Scheduler works in local time, so convert the target UTC hour.
$todayUtc = [DateTime]::UtcNow.Date.AddHours($UtcHour)
$localTime = [System.TimeZoneInfo]::ConvertTimeFromUtc($todayUtc, [System.TimeZoneInfo]::Local)
Write-Host "$UtcHour`:00 UTC is $($localTime.ToString('HH:mm')) local time ($([System.TimeZoneInfo]::Local.Id))."

# Logs go beside the repo so a failed overnight run leaves evidence.
$logDir = Join-Path $repo 'local\logs'
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

$wrapper = Join-Path $repo 'local\run-pipeline.cmd'
@"
@echo off
REM Generated by local\schedule-windows.ps1
cd /d "$repo"
for /f "tokens=2 delims==" %%I in ('wmic os get localdatetime /value') do set dt=%%I
set stamp=%dt:~0,8%-%dt:~8,4%
node "local\dist\pipeline.mjs" >> "local\logs\pipeline-%stamp%.log" 2>&1
"@ | Set-Content -Path $wrapper -Encoding ASCII

$action  = New-ScheduledTaskAction -Execute $wrapper -WorkingDirectory $repo
$trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek $DayOfWeek -At $localTime

# Wake the machine, and catch up if it was asleep at the scheduled moment,
# otherwise a laptop that was shut on Friday evening silently skips a week.
$settings = New-ScheduledTaskSettingsSet `
    -WakeToRun `
    -StartWhenAvailable `
    -DontStopOnIdleEnd `
    -ExecutionTimeLimit (New-TimeSpan -Hours 4) `
    -RestartCount 2 `
    -RestartInterval (New-TimeSpan -Minutes 15)

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Description 'Fetches trade statistics, analyses them, and publishes the results to Tereflow.' `
    -Force | Out-Null

Write-Host ""
Write-Host "Registered '$TaskName'." -ForegroundColor Green
Write-Host "  runs    $DayOfWeek at $($localTime.ToString('HH:mm')) local ($UtcHour`:00 UTC)"
Write-Host "  logs    $logDir"
Write-Host ""
Write-Host "Test it now with:"
Write-Host "    Start-ScheduledTask -TaskName $TaskName"
