<#
    Register the Tereflow pipeline as a Windows scheduled task.

    Runs every Friday at 21:00 GMT. The task is created in local time with the
    offset worked out for you, because Task Scheduler has no notion of UTC.

    Run this from an elevated PowerShell prompt, once:

        powershell -ExecutionPolicy Bypass -File local\schedule-windows.ps1

    To remove it:

        Unregister-ScheduledTask -TaskName Tereflow-Pipeline -Confirm:$false
#>

param(
    [string]$TaskName = 'Tereflow-Pipeline',
    # 21:00 GMT. Change only if you want a different publication time.
    [int]$UtcHour = 21,
    [string]$DayOfWeek = 'Friday'
)

$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot
$script = Join-Path $repo 'local\dist\pipeline.mjs'

if (-not (Test-Path $script)) {
    Write-Host "Pipeline is not built yet. Run this first:" -ForegroundColor Yellow
    Write-Host "    cd `"$repo`"" -ForegroundColor Yellow
    Write-Host "    npm run pipeline:build" -ForegroundColor Yellow
    exit 1
}

if (-not (Test-Path (Join-Path $repo 'local\.env'))) {
    Write-Host "local\.env is missing. Copy local\.env.example and fill it in." -ForegroundColor Yellow
    exit 1
}

$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node) { throw 'node is not on PATH.' }

# Task Scheduler triggers fire at a fixed LOCAL time and know nothing about UTC.
# The target is 21:00 GMT, and GMT does not shift, so a trigger set to today's
# equivalent local time drifts by an hour the moment daylight saving changes.
# Here 21:00 UTC is 17:00 in summer and 16:00 in winter: a task pinned to 17:00
# would publish at 22:00 UTC for half the year, which is not what "9pm GMT"
# means.
#
# So the trigger is set to whichever local time is EARLIER across the year, and
# the wrapper waits out the remainder. The task then starts at or before the
# target in every season and the actual run happens at 21:00 UTC year-round.
$utcTarget = [DateTime]::UtcNow.Date.AddHours($UtcHour)
$candidates = @(
    [System.TimeZoneInfo]::ConvertTimeFromUtc($utcTarget, [System.TimeZoneInfo]::Local),
    [System.TimeZoneInfo]::ConvertTimeFromUtc($utcTarget.AddMonths(6), [System.TimeZoneInfo]::Local)
)
$localNow = $candidates[0]
# Compare clock times, not dates: the two candidates are six months apart, and
# taking the later candidate wholesale would also take its date, pushing the
# first run half a year out. Only the time of day is wanted.
$earliest = if ($candidates[1].TimeOfDay -lt $candidates[0].TimeOfDay) { $candidates[1] } else { $candidates[0] }
$localTime = [DateTime]::Today.Add($earliest.TimeOfDay)
$drifts = $candidates[0].TimeOfDay -ne $candidates[1].TimeOfDay

Write-Host "$UtcHour`:00 UTC is $($localNow.ToString('HH:mm')) local right now ($([System.TimeZoneInfo]::Local.Id))."
if ($drifts) {
    Write-Host "Daylight saving moves that to $($candidates[1].ToString('HH:mm')) for part of the year." -ForegroundColor DarkGray
    Write-Host "Triggering at $($localTime.ToString('HH:mm')) and waiting for $UtcHour`:00 UTC, so the" -ForegroundColor DarkGray
    Write-Host "publication time holds in both seasons." -ForegroundColor DarkGray
}

# Logs go beside the repo so a failed overnight run leaves evidence.
$logDir = Join-Path $repo 'local\logs'
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

$wrapper = Join-Path $repo 'local\run-pipeline.cmd'
@"
@echo off
REM Generated by local\schedule-windows.ps1
cd /d "$repo"
for /f "tokens=2 delims==" %%I in ('wmic os get localdatetime /value') do set dt=%%I
set stamp=%dt:~0,8%-%dt:~8,4%

REM The trigger fires at the earlier of the two local times that $UtcHour`:00 UTC
REM maps to across the year, so in one season it arrives early. Wait out the
REM difference rather than publishing an hour ahead of the stated time.
REM
REM Deliberately one long line. A caret continuation inside a quoted string is
REM not honoured by cmd: the first attempt at this split the command across
REM lines and cmd tried to run "^" and "`$w" as separate programs.
powershell -NoProfile -ExecutionPolicy Bypass -Command "`$t = [DateTime]::UtcNow.Date.AddHours($UtcHour); if ([DateTime]::UtcNow -gt `$t) { `$t = `$t.AddDays(1) }; `$w = (`$t - [DateTime]::UtcNow).TotalSeconds; if (`$w -gt 0 -and `$w -lt 7200) { Write-Host ('Waiting {0:N0}s for $UtcHour`:00 UTC.' -f `$w); Start-Sleep -Seconds `$w }"

node "local\dist\pipeline.mjs" >> "local\logs\pipeline-%stamp%.log" 2>&1

REM Market context: population, spending power and sector mix, from the World
REM Bank. Runs after the trade pipeline and in its own step, because a failure
REM here must not discard a successful trade ingest. The trade figures are the
REM product; this is the background an investor reads them against.
REM
REM NOTE: this writes to the local D1 file directly. On a deployed instance it
REM needs the same treatment the trade pipeline already has, pushing finished
REM rows to the Worker rather than opening the database. Until then the context
REM panel is refreshed only where the scheduled task runs.
node "scripts\ingest-context.mjs" >> "local\logs\context-%stamp%.log" 2>&1
"@ | Set-Content -Path $wrapper -Encoding ASCII

$action  = New-ScheduledTaskAction -Execute $wrapper -WorkingDirectory $repo
$trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek $DayOfWeek -At $localTime

# Wake the machine, and catch up if it was asleep at the scheduled moment,
# otherwise a laptop that was shut on Friday evening silently skips a week.
$settings = New-ScheduledTaskSettingsSet `
    -WakeToRun `
    -StartWhenAvailable `
    -DontStopOnIdleEnd `
    -ExecutionTimeLimit (New-TimeSpan -Hours 4) `
    -RestartCount 2 `
    -RestartInterval (New-TimeSpan -Minutes 15)

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Description 'Fetches trade statistics, analyses them, and publishes the results to Tereflow.' `
    -Force | Out-Null

Write-Host ""
Write-Host "Registered '$TaskName'." -ForegroundColor Green
Write-Host "  runs    $DayOfWeek at $($localTime.ToString('HH:mm')) local ($UtcHour`:00 UTC)"
Write-Host "  logs    $logDir"
Write-Host ""
Write-Host "Test it now with:"
Write-Host "    Start-ScheduledTask -TaskName $TaskName"
