/**
 * Ghana, as configured. The only active country for this prototype.
 *
 * Everything Ghana-specific lives here so the analytics, scoring and
 * explanation layers stay country-agnostic. Adding Nigeria later should mean a
 * second file like this one, not edits scattered through the engine.
 *
 * The dimension and value strings below are not guesses. They were read from
 * the live endpoint metadata (see scripts/probe-statbank.mjs). PXWeb matches
 * these exactly, and a near-miss returns an empty cube rather than an error,
 * so they are pinned rather than reconstructed.
 */
import type { CountryConfig, PartnerMapping } from '../types';

/**
 * Partner names, mapped from this application's spelling to StatBank's.
 *
 * Generated by scripts/map-statbank-partners.mjs against the live dimension
 * list. Five of these differ from our own names, including the United States,
 * and a mismatch is invisible: the API happily returns a cube with nothing in
 * it, so that partner contributes zero to every share and every ranking with
 * nothing anywhere saying why.
 *
 * Palau, Vanuatu and Micronesia are in our country list but not in StatBank's
 * partner dimension. That is a real answer rather than a gap: Ghana does not
 * record trade with them.
 */
export const GHANA_PARTNERS: PartnerMapping[] = [
  { app_name: 'Algeria', source_name: 'Algeria', iso3: 'DZA' },
  { app_name: 'Angola', source_name: 'Angola', iso3: 'AGO' },
  { app_name: 'Argentina', source_name: 'Argentina', iso3: 'ARG' },
  { app_name: 'Australia', source_name: 'Australia', iso3: 'AUS' },
  { app_name: 'Austria', source_name: 'Austria', iso3: 'AUT' },
  { app_name: 'Bahamas', source_name: 'Bahamas', iso3: 'BHS' },
  { app_name: 'Bangladesh', source_name: 'Bangladesh', iso3: 'BGD' },
  { app_name: 'Barbados', source_name: 'Barbados', iso3: 'BRB' },
  { app_name: 'Belgium', source_name: 'Belgium', iso3: 'BEL' },
  { app_name: 'Bolivia', source_name: 'Bolivia', iso3: 'BOL' },
  { app_name: 'Brazil', source_name: 'Brazil', iso3: 'BRA' },
  { app_name: 'Cameroon', source_name: 'Cameroon', iso3: 'CMR' },
  { app_name: 'Canada', source_name: 'Canada', iso3: 'CAN' },
  { app_name: 'Chile', source_name: 'Chile', iso3: 'CHL' },
  { app_name: 'China', source_name: 'China', iso3: 'CHN' },
  { app_name: 'Colombia', source_name: 'Colombia', iso3: 'COL' },
  { app_name: 'Costa Rica', source_name: 'Costa Rica', iso3: 'CRI' },
  { app_name: "Cote d'Ivoire", source_name: 'Cote dIvoire', iso3: 'CIV' },
  { app_name: 'Cuba', source_name: 'Cuba', iso3: 'CUB' },
  { app_name: 'DR Congo', source_name: 'Democratic Republic of the Congo', iso3: 'COD' },
  { app_name: 'Denmark', source_name: 'Denmark', iso3: 'DNK' },
  { app_name: 'Dominican Republic', source_name: 'Dominican Republic', iso3: 'DOM' },
  { app_name: 'Ecuador', source_name: 'Ecuador', iso3: 'ECU' },
  { app_name: 'Egypt', source_name: 'Egypt', iso3: 'EGY' },
  { app_name: 'El Salvador', source_name: 'El Salvador', iso3: 'SLV' },
  { app_name: 'Ethiopia', source_name: 'Ethiopia', iso3: 'ETH' },
  { app_name: 'Fiji', source_name: 'Fiji', iso3: 'FJI' },
  { app_name: 'France', source_name: 'France', iso3: 'FRA' },
  { app_name: 'French Polynesia', source_name: 'French Polynesia', iso3: 'PYF' },
  { app_name: 'Germany', source_name: 'Germany', iso3: 'DEU' },
  { app_name: 'Guatemala', source_name: 'Guatemala', iso3: 'GTM' },
  { app_name: 'Guyana', source_name: 'Guyana', iso3: 'GUY' },
  { app_name: 'Haiti', source_name: 'Haiti', iso3: 'HTI' },
  { app_name: 'Honduras', source_name: 'Honduras', iso3: 'HND' },
  { app_name: 'India', source_name: 'India', iso3: 'IND' },
  { app_name: 'Indonesia', source_name: 'Indonesia', iso3: 'IDN' },
  { app_name: 'Ireland', source_name: 'Ireland', iso3: 'IRL' },
  { app_name: 'Israel', source_name: 'Israel', iso3: 'ISR' },
  { app_name: 'Italy', source_name: 'Italy', iso3: 'ITA' },
  { app_name: 'Jamaica', source_name: 'Jamaica', iso3: 'JAM' },
  { app_name: 'Japan', source_name: 'Japan', iso3: 'JPN' },
  { app_name: 'Kenya', source_name: 'Kenya', iso3: 'KEN' },
  { app_name: 'Kiribati', source_name: 'Kiribati', iso3: 'KIR' },
  { app_name: 'Libya', source_name: 'Libya', iso3: 'LBY' },
  { app_name: 'Malaysia', source_name: 'Malaysia', iso3: 'MYS' },
  { app_name: 'Marshall Islands', source_name: 'Marshall Islands', iso3: 'MHL' },
  { app_name: 'Mexico', source_name: 'Mexico', iso3: 'MEX' },
  { app_name: 'Morocco', source_name: 'Morocco', iso3: 'MAR' },
  { app_name: 'Netherlands', source_name: 'Netherlands', iso3: 'NLD' },
  { app_name: 'New Caledonia', source_name: 'New Caledonia', iso3: 'NCL' },
  { app_name: 'New Zealand', source_name: 'New Zealand', iso3: 'NZL' },
  { app_name: 'Nicaragua', source_name: 'Nicaragua', iso3: 'NIC' },
  { app_name: 'Nigeria', source_name: 'Nigeria', iso3: 'NGA' },
  { app_name: 'Norway', source_name: 'Norway', iso3: 'NOR' },
  { app_name: 'Panama', source_name: 'Panama', iso3: 'PAN' },
  { app_name: 'Papua New Guinea', source_name: 'Papua New Guinea', iso3: 'PNG' },
  { app_name: 'Paraguay', source_name: 'Paraguay', iso3: 'PRY' },
  { app_name: 'Peru', source_name: 'Peru', iso3: 'PER' },
  { app_name: 'Philippines', source_name: 'Philippines', iso3: 'PHL' },
  { app_name: 'Poland', source_name: 'Poland', iso3: 'POL' },
  { app_name: 'Samoa', source_name: 'Samoa', iso3: 'WSM' },
  { app_name: 'Saudi Arabia', source_name: 'Saudi Arabia', iso3: 'SAU' },
  { app_name: 'Senegal', source_name: 'Senegal', iso3: 'SEN' },
  { app_name: 'Singapore', source_name: 'Singapore', iso3: 'SGP' },
  { app_name: 'Solomon Islands', source_name: 'Solomon Islands', iso3: 'SLB' },
  { app_name: 'South Africa', source_name: 'South Africa', iso3: 'ZAF' },
  { app_name: 'South Korea', source_name: 'Republic of Korea', iso3: 'KOR' },
  { app_name: 'Spain', source_name: 'Spain', iso3: 'ESP' },
  { app_name: 'Suriname', source_name: 'Suriname', iso3: 'SUR' },
  { app_name: 'Sweden', source_name: 'Sweden', iso3: 'SWE' },
  { app_name: 'Switzerland', source_name: 'Switzerland', iso3: 'CHE' },
  { app_name: 'Taiwan', source_name: 'Taiwan', iso3: 'TWN' },
  { app_name: 'Tanzania', source_name: 'United Republic of Tanzania', iso3: 'TZA' },
  { app_name: 'Thailand', source_name: 'Thailand', iso3: 'THA' },
  { app_name: 'Tonga', source_name: 'Tonga', iso3: 'TON' },
  { app_name: 'Trinidad and Tobago', source_name: 'Trinidad and Tobago', iso3: 'TTO' },
  { app_name: 'Tunisia', source_name: 'Tunisia', iso3: 'TUN' },
  { app_name: 'Turkey', source_name: 'Turkiye', iso3: 'TUR' },
  { app_name: 'Uganda', source_name: 'Uganda', iso3: 'UGA' },
  { app_name: 'United Arab Emirates', source_name: 'United Arab Emirates', iso3: 'ARE' },
  { app_name: 'United Kingdom', source_name: 'United Kingdom', iso3: 'GBR' },
  { app_name: 'United States', source_name: 'United States of America', iso3: 'USA' },
  { app_name: 'Uruguay', source_name: 'Uruguay', iso3: 'URY' },
  { app_name: 'Venezuela', source_name: 'Venezuela', iso3: 'VEN' },
  { app_name: 'Vietnam', source_name: 'Viet Nam', iso3: 'VNM' },
  { app_name: 'Zambia', source_name: 'Zambia', iso3: 'ZMB' },
];

export const GHANA: CountryConfig = {
  code: 'GH',
  name: 'Ghana',
  iso3: 'GHA',

  provider: {
    type: 'statbank',
    endpoint: 'https://statsbank.statsghana.gov.gh/api/v1/en/Trade/trade_detail_hs2.px',
    dimensions: {
      valuation: 'Valuation_Parameter',
      flow: 'Tradeflow',
      year: 'Year',
      month: 'Month',
      product: 'HS_2_digit',
      partner: 'Partner_Country',
    },
    values: {
      value_usd: 'Value in US Dollars',
      weight_kg: 'Net weight in KG',
      flow_import: 'Import',
      flow_export: 'Export',
      all_months: 'All Months',
      all_products: 'All Products',
      all_partners: 'All Partner Countries',
      months: [
        'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December',
      ],
    },
  },

  classification: {
    system: 'HS',
    // HS2 is what this endpoint offers. It is a sector signal, not a product
    // one, and every opportunity built from it says so. A more granular Ghana
    // endpoint can be added later without touching the analytics.
    level: 'HS2',
  },

  // The endpoint currently carries 2021 to 2025. Listed rather than computed
  // so a run is reproducible and so a year appearing or disappearing upstream
  // is a visible change here rather than a silent one.
  years: ['2021', '2022', '2023', '2024', '2025'],

  partners: GHANA_PARTNERS,

  filters: {
    // Traditional commodities, excluded at chapter level because that is the
    // granularity this endpoint offers.
    //
    // Excluded rather than deleted: the rows are still stored and still
    // queryable, they are just kept out of the opportunity ranking, and each
    // one carries the reason. A filter nobody can inspect is a filter nobody
    // can correct.
    //
    // Note what is deliberately NOT here. Chapter 15 (fats and oils) stays in
    // even though crude palm oil is traditional, because refined and packaged
    // edible oil is exactly the import-substitution case this product exists
    // to find. The same reasoning keeps chapter 18 (cocoa) in: Ghana exports
    // beans and imports chocolate, and the second half of that sentence is the
    // opportunity.
    excluded: [
      { codes: ['26'], reason: 'Metal ores and concentrates. Extractive, not a manufacturing opportunity.' },
      { codes: ['27'], reason: 'Mineral fuels and oils. Ghana\'s traditional petroleum trade dominates any ranking it enters.' },
      { codes: ['71'], reason: 'Pearls, precious stones and metals. Gold is Ghana\'s largest export and swamps every comparison.' },
      { codes: ['72', '73'], reason: 'Iron and steel. Bulk commodity inputs priced on world markets rather than local demand.' },
      { codes: ['74', '75', '76', '78', '79', '80', '81'], reason: 'Base metals. Commodity trade rather than a product opportunity.' },
      { codes: ['88', '89'], reason: 'Aircraft and ships. Capital equipment with no plausible local substitution.' },
      { codes: ['93'], reason: 'Arms and ammunition.' },
      { codes: ['97'], reason: 'Works of art and antiques. Not a market that behaves like trade.' },
      { codes: ['98', '99'], reason: 'Unclassified and special transactions. Residual accounting lines, not products.' },
    ],
  },

  scoring: {
    // Sum to 1. The weights are a product judgement rather than a fact, which
    // is why they live in configuration where somebody who disagrees can move
    // one number instead of reading the scoring code.
    market_size: 0.30,
    growth: 0.25,
    import_dependency: 0.20,
    stability: 0.15,
    supplier_concentration: 0.10,
  },
};

/** Only Ghana is active. The registry exists so the second country is a file. */
export const ACTIVE_COUNTRIES: Record<string, CountryConfig> = {
  GH: GHANA,
};
