-- Worldwide traditional trade (not SME-accessible), decided from the Ghana, Peru, Sri Lanka and Bangladesh
-- export-promotion conventions, the primary-commodity and Kimberley Process / Wassenaar controls, and capital
-- intensity. It is a hide-by-default heuristic: traditional is defined per country by agencies, so these can be
-- overridden for one country or shown with the toggle. Codes are HS2 chapters where every heading qualifies and
-- HS4/HS6 headings where only part of a chapter does. A code covers every longer code beneath it.
--
-- Chapter 73 (articles of iron or steel) comes OFF the list: it is finished goods, and Ghana's export agency
-- counts iron and steel products as non-traditional. Primary iron and steel (72) stays on.
DELETE FROM export_classifications WHERE entity_id = '*' AND hs_code = '73';
INSERT OR IGNORE INTO export_classifications (id, entity_id, hs_code, category, note, source_label)
VALUES
  ('cls_default_2501', '*', '2501', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2502', '*', '2502', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2503', '*', '2503', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2504', '*', '2504', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2505', '*', '2505', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2506', '*', '2506', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2507', '*', '2507', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2508', '*', '2508', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2509', '*', '2509', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2510', '*', '2510', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2511', '*', '2511', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2512', '*', '2512', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2513', '*', '2513', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2514', '*', '2514', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2517', '*', '2517', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2518', '*', '2518', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2519', '*', '2519', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2520', '*', '2520', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2521', '*', '2521', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2522', '*', '2522', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2523', '*', '2523', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2524', '*', '2524', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2525', '*', '2525', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2526', '*', '2526', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2528', '*', '2528', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2529', '*', '2529', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_2530', '*', '2530', 'traditional', 'Raw minerals, salt, sulphur, earths, cement and plaster. Quarried or mined in bulk, low value per tonne. Marble and granite (2515, 2516) are left open.', 'Tereflow SME exemption'),
  ('cls_default_24', '*', '24', 'traditional', 'Tobacco and manufactured substitutes. Licensed and excise-controlled; raw leaf is contract-farmed.', 'Tereflow SME exemption'),
  ('cls_default_30', '*', '30', 'traditional', 'Pharmaceutical products. Licensed and registered by national regulators, so not open to a newcomer.', 'Tereflow SME exemption'),
  ('cls_default_31', '*', '31', 'traditional', 'Fertilisers. Bulk commodity, often state-procured or subsidised.', 'Tereflow SME exemption'),
  ('cls_default_36', '*', '36', 'traditional', 'Explosives, pyrotechnics and matches. Licensed and controlled.', 'Tereflow SME exemption'),
  ('cls_default_47', '*', '47', 'traditional', 'Pulp of wood and fibrous material. Bulk commodity from large mills.', 'Tereflow SME exemption'),
  ('cls_default_86', '*', '86', 'traditional', 'Railway and tramway locomotives and rolling stock. Capital equipment sold to railways and governments.', 'Tereflow SME exemption'),
  ('cls_default_0902', '*', '0902', 'traditional', 'Tea. Bulk commodity traded through auctions and large estates.', 'Tereflow SME exemption'),
  ('cls_default_090111', '*', '090111', 'traditional', 'Coffee, not roasted, not decaffeinated. Bulk green coffee traded through exchanges and large exporters.', 'Tereflow SME exemption'),
  ('cls_default_090112', '*', '090112', 'traditional', 'Coffee, not roasted, decaffeinated. Bulk green coffee.', 'Tereflow SME exemption'),
  ('cls_default_1001', '*', '1001', 'traditional', 'Wheat and meslin. Bulk grain traded by a few large merchants.', 'Tereflow SME exemption'),
  ('cls_default_1201', '*', '1201', 'traditional', 'Soya beans. Bulk oilseed traded by a few large merchants.', 'Tereflow SME exemption'),
  ('cls_default_1205', '*', '1205', 'traditional', 'Rape or colza seeds. Bulk oilseed.', 'Tereflow SME exemption'),
  ('cls_default_151110', '*', '151110', 'traditional', 'Crude palm oil. Bulk commodity from plantation-scale producers and refiners.', 'Tereflow SME exemption'),
  ('cls_default_170111', '*', '170111', 'traditional', 'Raw cane sugar. Bulk, quota-linked and state-influenced.', 'Tereflow SME exemption'),
  ('cls_default_170112', '*', '170112', 'traditional', 'Raw beet sugar. Bulk, quota-linked and state-influenced.', 'Tereflow SME exemption'),
  ('cls_default_1801', '*', '1801', 'traditional', 'Cocoa beans. State-controlled marketing in the main producing countries (for example COCOBOD in Ghana). Cocoa paste, butter and powder stay open.', 'Tereflow SME exemption'),
  ('cls_default_2844', '*', '2844', 'traditional', 'Radioactive chemical elements and isotopes. Controlled nuclear material.', 'Tereflow SME exemption'),
  ('cls_default_2845', '*', '2845', 'traditional', 'Isotopes and their compounds. Controlled nuclear material.', 'Tereflow SME exemption'),
  ('cls_default_2939', '*', '2939', 'traditional', 'Plant alkaloids including opiates. Controlled substances under the UN drug conventions.', 'Tereflow SME exemption'),
  ('cls_default_4001', '*', '4001', 'traditional', 'Natural rubber. Bulk plantation commodity.', 'Tereflow SME exemption'),
  ('cls_default_4401', '*', '4401', 'traditional', 'Fuel wood, wood chips and waste. Bulk forestry commodity.', 'Tereflow SME exemption'),
  ('cls_default_4403', '*', '4403', 'traditional', 'Wood in the rough (logs). Concession-based and often export-restricted.', 'Tereflow SME exemption'),
  ('cls_default_5201', '*', '5201', 'traditional', 'Cotton, not carded or combed. Bulk raw fibre. Yarn and fabric stay open.', 'Tereflow SME exemption'),
  ('cls_default_8401', '*', '8401', 'traditional', 'Nuclear reactors and their fuel elements. Controlled capital equipment.', 'Tereflow SME exemption'),
  ('cls_default_8410', '*', '8410', 'traditional', 'Hydraulic turbines. Power-plant capital equipment.', 'Tereflow SME exemption'),
  ('cls_default_8411', '*', '8411', 'traditional', 'Turbojets, turbopropellers and gas turbines. Aerospace and power-plant capital equipment.', 'Tereflow SME exemption'),
  ('cls_default_8426', '*', '8426', 'traditional', 'Ships'' derricks, cranes and lifting frames. Heavy capital equipment.', 'Tereflow SME exemption'),
  ('cls_default_8429', '*', '8429', 'traditional', 'Bulldozers, graders, excavators and similar self-propelled machinery. Heavy capital equipment.', 'Tereflow SME exemption'),
  ('cls_default_8430', '*', '8430', 'traditional', 'Other earth-moving, boring and mining machinery. Heavy capital equipment.', 'Tereflow SME exemption'),
  ('cls_default_8701', '*', '8701', 'traditional', 'Tractors. Agricultural and road tractors, a capital purchase typically financed or procured by institutions.', 'Tereflow SME exemption'),
  ('cls_default_8705', '*', '8705', 'traditional', 'Special-purpose motor vehicles (cranes, drilling, concrete). Heavy capital equipment.', 'Tereflow SME exemption'),
  ('cls_default_8710', '*', '8710', 'traditional', 'Tanks and other armoured fighting vehicles. Arms.', 'Tereflow SME exemption');
