-- TradeAtlas playbooks
-- Generated by scripts/build-playbooks.mjs from verified research output.
-- Every claim is attributed to a real institutional publication, checked live.

DELETE FROM playbooks;

INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_export-readiness-basics', 'export-readiness-basics', 'Becoming export-ready: the standard sequence', NULL, NULL, NULL, 'The step by step path a small business follows to go from selling locally to shipping its first international order. Covers demand checking, product classification, quality infrastructure, and the institutions that will help you free of charge.', '## Step 1: Confirm there is demand before you spend anything

Do not start with your product. Start with the trade data. ITC Trade Map holds annual, quarterly and monthly trade flows for over 220 countries and territories and around 5,300 products, with time series going back to 2001. Look up who already imports your product in volume, whether their imports are growing, and what unit values they pay. If nobody near you is buying it and the trend is flat, pick a different market before you spend money on samples or certification.

Source: [ITC Trade Map](https://www.intracen.org/resources/tools/trade-map) · [Trade Map](https://www.trademap.org/)

## Step 2: Get your HS code right, because everything else depends on it

The Harmonized System code is the number customs authorities use to classify your product. Trade Map works at the two, four and six digit level of the HS. Every tariff, every permit, every standard and every certificate is tied to that code. Get it wrong and you will be quoted the wrong duty, miss a required certificate, and have your consignment held. Confirm the code with your national customs authority in writing before you quote a buyer.

Source: [ITC Trade Map](https://www.intracen.org/resources/tools/trade-map)

## Step 3: Check the tariff and the rules you must meet in the target market

ITC Market Access Map lets you compare tariffs across countries, including ad valorem equivalents for duties that are not expressed as a percentage, and tariff rate quotas. It also carries regulatory requirements and the texts of rules of origin with their corresponding certificates of origin. Use it to work out your landed cost before you promise a price. A low tariff is meaningless if the regulatory requirements are ones you cannot meet.

Source: [ITC Market Access Map](https://www.intracen.org/resources/tools/market-access-map) · [Market Access Map](https://www.macmap.org/)

## Step 4: Understand the quality infrastructure you sit inside

Buyers do not just want your product. They want proof it meets a standard, issued by a body they trust. The ITC guide on export quality management explains standardization, conformity assessment, metrology, technical regulations, accreditation, sanitary and phytosanitary measures, and the WTO agreements on technical barriers to trade, in a question and answer format aimed at exporters in developing countries. Read it before you pay any consultant, because it will tell you which of these you actually need.

Source: [Export Quality Management: An Answer Book for Small and Medium-Sized Exporters](https://www.intracen.org/resources/publications/export-quality-management-a-guide-for-small-and-medium-sized-exporters-1)

## Step 5: Use the free training and the free helpdesk

ITC runs the SME Trade Academy, a public learning platform with more than 100 free online courses covering export development, sustainability, e-commerce and market analysis, aimed at micro, small and medium enterprises in developing and least developed countries. The Global Trade Helpdesk brings tariff, requirement and market information into a single portal. Both cost nothing. Work through them before you hire advisers.

Source: [ITC SME Trade Academy](https://www.intracen.org/resources/tools/sme-trade-academy) · [Global Trade Helpdesk](https://globaltradehelpdesk.org/en)

## Step 6: Know that the system is being actively simplified for firms your size

Small business trade barriers are a live agenda item at the WTO. As of May 2026 there were 106 WTO members participating in the Informal Working Group on MSMEs, accounting for around 90 percent of world exports. Its 2020 package pushes members to support the Global Trade Helpdesk, implement the Trade Facilitation Agreement, and improve MSME access to finance and cross border payments. If a border procedure looks arbitrary, there is a good chance a formal simplification commitment already covers it.

Source: [Micro, small and medium-sized enterprises (MSMEs)](https://www.wto.org/english/tratop_e/msmes_e/msmes_e.htm) · [Trade Facilitation Agreement](https://www.wto.org/english/tratop_e/tradfa_e/tradfa_e.htm)', '[{"title":"ITC Trade Map","url":"https://www.intracen.org/resources/tools/trade-map","publisher":"International Trade Centre"},{"title":"Trade Map","url":"https://www.trademap.org/","publisher":"International Trade Centre"},{"title":"Export Quality Management: An Answer Book for Small and Medium-Sized Exporters","url":"https://www.intracen.org/resources/publications/export-quality-management-a-guide-for-small-and-medium-sized-exporters-1","publisher":"International Trade Centre"},{"title":"ITC Market Access Map","url":"https://www.intracen.org/resources/tools/market-access-map","publisher":"International Trade Centre"},{"title":"WTO MSME work programme","url":"https://www.wto.org/english/tratop_e/msmes_e/msmes_e.htm","publisher":"World Trade Organization"},{"title":"World Bank trade topic page","url":"https://www.worldbank.org/ext/en/topic/trade","publisher":"World Bank Group"},{"title":"Market Access Map","url":"https://www.macmap.org/","publisher":"International Trade Centre"},{"title":"ITC SME Trade Academy","url":"https://www.intracen.org/resources/tools/sme-trade-academy","publisher":"International Trade Centre"},{"title":"Global Trade Helpdesk","url":"https://globaltradehelpdesk.org/en","publisher":"International Trade Centre / WTO / UNCTAD"},{"title":"Trade Facilitation Agreement","url":"https://www.wto.org/english/tratop_e/tradfa_e/tradfa_e.htm","publisher":"World Trade Organization"}]', 'Compiled from institutional trade guidance', 'International Trade Centre, World Trade Organization, World Bank Group, International Trade Centre / WTO / UNCTAD', 0, 3, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_export-documentation-pack', 'export-documentation-pack', 'The documents an export shipment actually needs', NULL, NULL, NULL, 'What paperwork travels with a consignment, who issues each document, and which ones stop the shipment dead if they are missing or inconsistent.', '## Step 1: Treat the document set as one consistent story

Customs and banks check your documents against each other. The product description, quantity, weight, value and HS code must match on every single one. A packing list that says 980 cartons and an invoice that says 1000 will get the consignment held and can get a letter of credit payment refused. Build one master data sheet per shipment and copy from it. Do not retype.

Source: [Trade Facilitation Agreement](https://www.wto.org/english/tratop_e/tradfa_e/tradfa_e.htm)

## Step 2: Commercial invoice and packing list

You issue both yourself. The commercial invoice is the legal statement of what was sold, to whom, at what price, on what Incoterm, and is what customs uses to assess duty. The packing list breaks the same consignment down by carton, weight and dimension so the carrier and the inspector can physically verify it. Put your HS code and the Incoterms 2020 rule with the named place on the invoice. Ambiguity here is the single most common cause of disputes.

Source: [Incoterms 2020](https://iccwbo.org/business-solutions/incoterms-rules/incoterms-2020/)

## Step 3: Certificate of origin

This states where the goods were produced. It decides whether your buyer pays the normal tariff or a preferential one under a trade agreement. Rules of origin differ by agreement, so the same product can qualify under one deal and fail under another. ITC publishes the texts of rules of origin with their corresponding certificates of origin, and runs the Rules of Origin Facilitator for checking product specific rules. Confirm which certificate form your buyer needs before you ship.

Source: [ITC Market Access Map](https://www.intracen.org/resources/tools/market-access-map) · [Rules of Origin Facilitator](https://findrulesoforigin.org/)

## Step 4: Phytosanitary certificate for plants and plant products

If you are exporting plants, fruit, vegetables, seeds, nuts or wood, the importing country will almost certainly require a phytosanitary certificate. It is issued only by your country''s national plant protection organisation, not by you and not by your buyer. The framework is the International Plant Protection Convention. The EU has its own plant health rules aimed at preventing the introduction of quarantine pests, and applies them to imports. Apply early, because inspection has to happen before the goods leave.

Source: [International Plant Protection Convention](https://www.ippc.int/en/) · [Plant health and biosecurity](https://food.ec.europa.eu/plants/plant-health-and-biosecurity_en)

## Step 5: Transport document: bill of lading or air waybill

The carrier issues this, not you. For sea freight it is a bill of lading, and an original negotiable bill of lading is a document of title, meaning whoever holds it can claim the goods. For air freight it is an air waybill, which is a receipt and contract of carriage but not a document of title. This distinction matters enormously for payment security. If you are relying on documents to control the goods until you are paid, sea freight with an original bill of lading gives you leverage that air freight does not.

Source: [ICC trade finance](https://iccwbo.org/global-insights/trade-finance/)

## Step 6: Export declaration and the single window

Your own government requires a customs export declaration before the goods leave. Many countries now run an electronic single window so you file once instead of visiting each agency. Kenya''s National Electronic Single Window System is operated by the Kenya Trade Network Agency under the National Treasury. Find out whether your country has an equivalent and register on it before your first shipment, because account approval takes time.

Source: [Kenya Trade Network Agency (KenTrade)](https://kentrade.go.ke/) · [Trade Facilitation Agreement](https://www.wto.org/english/tratop_e/tradfa_e/tradfa_e.htm)', '[{"title":"Trade Facilitation Agreement","url":"https://www.wto.org/english/tratop_e/tradfa_e/tradfa_e.htm","publisher":"World Trade Organization"},{"title":"Incoterms 2020","url":"https://iccwbo.org/business-solutions/incoterms-rules/incoterms-2020/","publisher":"International Chamber of Commerce"},{"title":"Rules of Origin Facilitator","url":"https://findrulesoforigin.org/","publisher":"International Trade Centre"},{"title":"International Plant Protection Convention","url":"https://www.ippc.int/en/","publisher":"IPPC Secretariat, FAO"},{"title":"KenTrade single window","url":"https://kentrade.go.ke/","publisher":"Kenya Trade Network Agency"},{"title":"ITC Market Access Map","url":"https://www.intracen.org/resources/tools/market-access-map","publisher":"International Trade Centre"},{"title":"Plant health and biosecurity","url":"https://food.ec.europa.eu/plants/plant-health-and-biosecurity_en","publisher":"European Commission"},{"title":"ICC trade finance","url":"https://iccwbo.org/global-insights/trade-finance/","publisher":"International Chamber of Commerce"}]', 'Compiled from institutional trade guidance', 'World Trade Organization, International Chamber of Commerce, International Trade Centre, IPPC Secretariat, FAO, Kenya Trade Network Agency, European Commission', 0, 3, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_incoterms-2020-in-practice', 'incoterms-2020-in-practice', 'Incoterms 2020: choosing the right three letters', NULL, NULL, NULL, 'How the ICC delivery terms allocate cost, risk and responsibility between seller and buyer, and which ones a first time exporter should and should not agree to.', '## Step 1: Understand what an Incoterms rule does and does not do

The Incoterms rules are published by the International Chamber of Commerce and are the global standard for allocating delivery obligations, cost and risk transfer between seller and buyer. They do not transfer ownership, they do not set the price, and they are not a contract on their own. They tell you the exact point at which risk passes from you to the buyer. Always write the rule with a named place, for example FOB Tema, not just FOB.

Source: [Incoterms 2020](https://iccwbo.org/business-solutions/incoterms-rules/incoterms-2020/)

## Step 2: Start with EXW or FCA if you have never shipped before

Under EXW the buyer collects from your premises and takes on almost everything. Under FCA you hand over to a carrier the buyer nominates. Both keep your obligations small while you learn. The trade off is that you have less control and usually a lower price. Many first time exporters agree to CIF because it sounds more professional, then discover they have committed to arranging and paying for ocean freight and insurance they do not know how to price.

Source: [Incoterms rules](https://iccwbo.org/business-solutions/incoterms-rules/)

## Step 3: Never quote a price without stating the Incoterm

A price of 2,000 dollars per tonne means nothing on its own. Ex works it might be profitable and delivered duty paid it might be a heavy loss. Build a costing sheet that starts with your factory gate cost and adds inland transport, handling, documentation, customs, freight, insurance and destination charges line by line. Then you can quote any Incoterm knowingly rather than guessing.

Source: [Incoterms 2020](https://iccwbo.org/business-solutions/incoterms-rules/incoterms-2020/)

## Step 4: Match the Incoterm to the mode of transport

Some rules are for any mode of transport and some are only for sea and inland waterway. Using a sea only rule for an air shipment creates a contract that does not describe what actually happens, which is exactly the situation that produces arguments about who pays for a loss. Check the ICC classification for the rule you intend to use before you sign.

Source: [Incoterms rules](https://iccwbo.org/business-solutions/incoterms-rules/)

## Step 5: Write the Incoterm identically on every document

The rule, the named place and the version year must appear the same way on the proforma, the sales contract, the commercial invoice and any letter of credit. Banks examining documents under a letter of credit reject on discrepancies. Writing Incoterms 2020 explicitly avoids a later argument about which edition applies.

Source: [Incoterms 2020](https://iccwbo.org/business-solutions/incoterms-rules/incoterms-2020/) · [ICC trade finance](https://iccwbo.org/global-insights/trade-finance/)', '[{"title":"Incoterms 2020","url":"https://iccwbo.org/business-solutions/incoterms-rules/incoterms-2020/","publisher":"International Chamber of Commerce"},{"title":"Incoterms rules overview","url":"https://iccwbo.org/business-solutions/incoterms-rules/","publisher":"International Chamber of Commerce"},{"title":"ICC trade finance","url":"https://iccwbo.org/global-insights/trade-finance/","publisher":"International Chamber of Commerce"}]', 'Compiled from institutional trade guidance', 'International Chamber of Commerce', 1, 2, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_getting-paid-trade-finance', 'getting-paid-trade-finance', 'Getting paid: payment methods and their risk trade-offs', NULL, NULL, NULL, 'The four ways a cross border sale gets paid, ranked by how much risk each puts on you, and how to pick one for a buyer you do not yet know.', '## Step 1: Accept that payment risk is the real risk

Trade finance exists because the seller wants to be paid before shipping and the buyer wants the goods before paying. The ICC describes these instruments, including letters of credit, export guarantees and supply chain finance, as the tools that let banks and businesses manage that risk so sellers get paid and buyers receive goods. The ICC is the standard setter that writes the rules making these transactions predictable and enforceable across jurisdictions. Your job is to pick the point on the spectrum that matches how much you trust the buyer.

Source: [ICC trade finance](https://iccwbo.org/global-insights/trade-finance/)

## Step 2: Advance payment is safest for you and hardest to get

The buyer pays before you ship. All the risk sits with them, which is why only a buyer who badly wants your product will agree. A workable middle path for a first order is a partial advance, for example 30 percent on order confirmation and the balance against shipping documents. Ask for it in writing in the proforma invoice. Many first orders from serious buyers do include a deposit.

Source: [ICC trade finance](https://iccwbo.org/global-insights/trade-finance/)

## Step 3: Letter of credit shifts the risk to a bank

Under a documentary credit the buyer''s bank undertakes to pay you provided you present documents that comply exactly with the credit terms. You are no longer relying on the buyer''s willingness to pay, you are relying on a bank''s undertaking. The cost is fees and absolute precision. Banks pay against documents, not against goods, so a single inconsistent date or description gives grounds for refusal. Read the credit the day you receive it and ask for amendments before you ship, not after.

Source: [ICC trade finance](https://iccwbo.org/global-insights/trade-finance/)

## Step 4: Documentary collection is cheaper and weaker

You ship, then send the documents through the banking channel with instructions to release them to the buyer against payment or against acceptance of a bill of exchange. The banks handle documents but do not guarantee payment. If the buyer simply refuses, your goods are sitting in a foreign port and you must find another buyer or pay to bring them home. Use it with a buyer you have already been paid by, not a new one.

Source: [ICC trade finance](https://iccwbo.org/global-insights/trade-finance/)

## Step 5: Open account is what large buyers will demand eventually

You ship and invoice, and the buyer pays 30, 60 or 90 days later. This is normal in established supply chains and puts all the risk on you. Do not offer it on a first order. When you do move to open account, look at credit insurance or receivables finance so you are not funding a large buyer out of your own working capital.

Source: [ICC trade finance](https://iccwbo.org/global-insights/trade-finance/)

## Step 6: Know why your bank prices trade finance the way it does

The ICC Trade Register supplies regulators and investors with multibank data evidencing historically low loss and default rates on trade and export finance across products and regions. ICC''s stated position is that aligning capital and liquidity requirements with that evidence would free bank capacity to serve SMEs and emerging markets and reduce the financing gap. If your bank tells you trade finance is inherently high risk, the industry data says otherwise, and it is reasonable to shop around.

Source: [ICC trade finance](https://iccwbo.org/global-insights/trade-finance/) · [WTO MSME work programme](https://www.wto.org/english/tratop_e/msmes_e/msmes_e.htm)', '[{"title":"ICC trade finance","url":"https://iccwbo.org/global-insights/trade-finance/","publisher":"International Chamber of Commerce"},{"title":"WTO MSME work programme","url":"https://www.wto.org/english/tratop_e/msmes_e/msmes_e.htm","publisher":"World Trade Organization"}]', 'Compiled from institutional trade guidance', 'International Chamber of Commerce, World Trade Organization', 1, 3, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_eu-food-safety-market-access', 'eu-food-safety-market-access', 'Selling food into the EU: the rules that block African exporters', 'Agriculture & food', NULL, NULL, 'The EU requirements that most often cause rejection at the border for agricultural consignments, and what to check before you ship.', '## Step 1: Start from the SPS and TBT framework, not from the buyer''s email

Under the WTO Sanitary and Phytosanitary Measures Agreement, countries set their own food safety and plant health standards but those regulations must be based on science, applied only to the extent necessary to protect health, and not applied in an arbitrarily discriminatory way. Members are encouraged to use international standards where they exist. This means EU requirements are published, reviewable and testable. You can find out in advance exactly what you must meet.

Source: [Food, animal and plant products: how safe is safe?](https://www.wto.org/english/thewto_e/whatis_e/tif_e/agrm4_e.htm) · [Codex Alimentarius](https://www.fao.org/fao-who-codexalimentarius/en/)

## Step 2: Check maximum residue levels for every pesticide your farmers use

The EU sets maximum residue levels for pesticides in food. A residue above the limit means rejection, regardless of how good the product otherwise is. The list changes, and the Commission acts on new scientific opinions from EFSA. Get your produce tested at an accredited laboratory against the current EU limits before shipping, and keep spray records from every farm in your supply base so you can trace a failure back to its source.

Source: [Maximum residue levels](https://food.ec.europa.eu/plants/pesticides/maximum-residue-levels_en) · [Codex Alimentarius](https://www.fao.org/fao-who-codexalimentarius/en/)

## Step 3: Clear the plant health requirements

EU plant health rules aim to protect crops, fruits, vegetables, flowers, ornamentals and forests from quarantine pests by preventing their introduction into the EU. The EU is a member of the International Plant Protection Convention and participates in setting international plant health standards. In practice this means your consignment needs a phytosanitary certificate from your national plant protection organisation and must be free of the specific pests the EU regulates. Confirm the pest list for your product and origin before harvest, not at the port.

Source: [Plant health and biosecurity](https://food.ec.europa.eu/plants/plant-health-and-biosecurity_en) · [International Plant Protection Convention](https://www.ippc.int/en/)

## Step 4: Do not use the word organic unless you are certified for the EU

For an imported product to be sold as organic in the EU it must fulfil all requirements of EU organic legislation. A small number of countries have trade agreements or equivalence arrangements with the EU. For products from any other country, inspection and certification must be carried out by control bodies or control authorities that are recognised and supervised by the European Commission. If you are in Ghana, Nigeria, Kenya or Cote d''Ivoire, that is the route that applies to you. Contact a Commission recognised control body before you make any organic claim.

Source: [Trade in organic products](https://agriculture.ec.europa.eu/farming/organic-farming/trade_en) · [Organic farming at a glance](https://agriculture.ec.europa.eu/farming/organic-farming/organics-glance_en)

## Step 5: Expect to be inspected at least once a year if certified

The EU organic system requires that producers, distributors and marketers register with a control body before marketing food as organic, are inspected and then awarded a certificate, and are checked at least once a year thereafter. Budget for recurring audit costs, not a one off fee. Certification is a running operational commitment, not a document you buy once.

Source: [Organic farming at a glance](https://agriculture.ec.europa.eu/farming/organic-farming/organics-glance_en)

## Step 6: Look up your specific product''s requirements, do not generalise

Requirements differ by HS code and by country of origin. ITC Market Access Map carries regulatory requirements alongside tariffs, and the Global Trade Helpdesk consolidates market requirement information for smaller firms. Run your exact HS code and your exact origin country through these before you commit to a buyer''s delivery date.

Source: [ITC Market Access Map](https://www.intracen.org/resources/tools/market-access-map) · [Global Trade Helpdesk](https://globaltradehelpdesk.org/en)', '[{"title":"WTO SPS and TBT explainer","url":"https://www.wto.org/english/thewto_e/whatis_e/tif_e/agrm4_e.htm","publisher":"World Trade Organization"},{"title":"Codex Alimentarius","url":"https://www.fao.org/fao-who-codexalimentarius/en/","publisher":"FAO / WHO"},{"title":"EU maximum residue levels","url":"https://food.ec.europa.eu/plants/pesticides/maximum-residue-levels_en","publisher":"European Commission"},{"title":"EU plant health and biosecurity","url":"https://food.ec.europa.eu/plants/plant-health-and-biosecurity_en","publisher":"European Commission"},{"title":"EU trade in organic products","url":"https://agriculture.ec.europa.eu/farming/organic-farming/trade_en","publisher":"European Commission"},{"title":"International Plant Protection Convention","url":"https://www.ippc.int/en/","publisher":"IPPC Secretariat, FAO"},{"title":"Organic farming at a glance","url":"https://agriculture.ec.europa.eu/farming/organic-farming/organics-glance_en","publisher":"European Commission"},{"title":"ITC Market Access Map","url":"https://www.intracen.org/resources/tools/market-access-map","publisher":"International Trade Centre"},{"title":"Global Trade Helpdesk","url":"https://globaltradehelpdesk.org/en","publisher":"International Trade Centre / WTO / UNCTAD"}]', 'Compiled from institutional trade guidance', 'World Trade Organization, FAO / WHO, European Commission, IPPC Secretariat, FAO, International Trade Centre, International Trade Centre / WTO / UNCTAD', 1, 3, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_us-fsma-food-imports', 'us-fsma-food-imports', 'Selling food into the United States: FSMA basics', 'Agriculture & food', NULL, NULL, 'How the US Food Safety Modernization Act shifts responsibility onto your American importer, and what that means for the records and systems you must be able to produce.', '## Step 1: Understand that your US importer is legally on the hook for you

Under the FDA Foreign Supplier Verification Programs rule, the US importer must verify their foreign supplier. That means your buyer is legally required to obtain evidence that you produce food to a standard the FDA accepts. This is why serious American buyers ask hard questions about your food safety system before they discuss price. Treat those questions as the deal, not as an obstacle to the deal.

Source: [FSMA Final Rule on Foreign Supplier Verification Programs (FSVP)](https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-foreign-supplier-verification-programs-fsvp-importers-food-humans-and-animals)

## Step 2: Know which records your importer will need from you

The FDA publishes a list of records required by the FSVP regulation and operates an Importer Portal for FSVP records submission. Your importer will ask you for the underlying evidence: hazard analysis, control measures, monitoring records, corrective actions, and test results. Build these as ordinary business records from day one. Reconstructing them retrospectively when your importer is audited is how relationships end.

Source: [FSMA Final Rule on Foreign Supplier Verification Programs (FSVP)](https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-foreign-supplier-verification-programs-fsvp-importers-food-humans-and-animals)

## Step 3: If you grow produce, read the Produce Safety rule

The FDA Produce Safety rule sets requirements for covered farms, with compliance dates staged by farm size based on the average annual monetary value of produce sold over the previous three years. Sprouts have separate, earlier and additional requirements. Agricultural water requirements have their own compliance dates. Work out which size band you fall into and which subparts apply to your crop before you approach a US buyer.

Source: [FSMA Final Rule on Produce Safety](https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-produce-safety)

## Step 4: Use the FDA''s own free assistance channels

The FDA operates the FSMA Technical Assistance Network as a central source of information for questions on FSMA rules, programs and implementation. It has also worked with the Food Safety Preventive Controls Alliance to develop training materials for importers and others. Send your specific question there rather than paying a consultant to interpret the rule for you at the start.

Source: [FSMA Final Rule on Foreign Supplier Verification Programs (FSVP)](https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-foreign-supplier-verification-programs-fsvp-importers-food-humans-and-animals)

## Step 5: Confirm the pre-arrival notification and registration steps with FDA directly

The United States requires advance notification of imported food shipments and registration of food facilities. These procedures and their web pages change, and getting the current requirement wrong will cause a shipment to be refused at the port. Have your US importer or customs broker confirm the current prior notice and facility registration obligations with FDA in writing for your specific product before your first shipment.

Source: [FSMA Final Rule on Foreign Supplier Verification Programs (FSVP)](https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-foreign-supplier-verification-programs-fsvp-importers-food-humans-and-animals)', '[{"title":"FSMA Foreign Supplier Verification Programs rule","url":"https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-foreign-supplier-verification-programs-fsvp-importers-food-humans-and-animals","publisher":"US Food and Drug Administration"},{"title":"FSMA Produce Safety rule","url":"https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-produce-safety","publisher":"US Food and Drug Administration"}]', 'Compiled from institutional trade guidance', 'US Food and Drug Administration', 1, 2, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_certification-globalgap-and-buyers', 'certification-globalgap-and-buyers', 'Buyer certifications: GLOBALG.A.P., Rainforest Alliance and Fairtrade', 'Agriculture & food', NULL, NULL, 'The voluntary certifications European and North American buyers ask for, what each one actually covers, and how to decide which to pursue first.', '## Step 1: Separate legal requirements from buyer requirements

Pesticide limits and phytosanitary certificates are law. GLOBALG.A.P., Rainforest Alliance and Fairtrade are voluntary schemes that individual buyers choose to demand. You can legally export without them. You often cannot sell to a European supermarket without at least one of them. Find out what your target buyer requires before you spend money, because certifying for the wrong scheme is a common and expensive mistake.

Source: [GLOBALG.A.P.](https://globalgap.org/)

## Step 2: GLOBALG.A.P. is the baseline for fresh produce

GLOBALG.A.P. sets standards for primary production and the supply chain, covering fruits, flowers, fish and feed, based on a third party certification system developed with sector stakeholders and supported by an IT platform. Its stated impact areas include food safety, environment, worker health, safety and welfare, animal welfare, supply chain transparency and capacity building. For horticulture into European retail, this is usually the first certification a buyer asks about.

Source: [GLOBALG.A.P.](https://globalgap.org/)

## Step 3: Rainforest Alliance is about farm sustainability and deforestation

The Rainforest Alliance runs sustainability programs and certification aimed at protecting forests and partnering with local communities, on the basis that farming causes nearly 80 percent of global deforestation. Its Sustainable Agriculture Standard Farm Requirements are the binding document for certificate holders, providing a framework covering crop productivity, sustainability performance data and risk based investment. If you are in cocoa or coffee, this is the scheme most commonly requested.

Source: [Rainforest Alliance](https://www.rainforest-alliance.org/) · [Rainforest Alliance Sustainable Agriculture Standard - Farm Requirements](https://knowledge.rainforest-alliance.org/docs/en/certification-standard-current)

## Step 4: Fairtrade is about producer economics

Fairtrade certification covers products including cocoa, sugar, bananas, cinnamon and coffee, and is framed around supporting the development of sustainable communities, protecting natural resources and improving farmer livelihoods. It is generally a fit for organised smallholder groups and cooperatives rather than a single trading company. If your supply base is a cooperative, this is worth investigating.

Source: [Fairtrade International](https://www.fairtrade.net/us-en.html)

## Step 5: Read the actual standard document before committing

Every scheme publishes its binding requirements. Rainforest Alliance publishes its Farm Requirements openly and in multiple languages. Download the standard, go through it clause by clause against how your farms actually operate, and count how many gaps you have. That gap count, not the certification fee, is the real cost. If you cannot close the gaps within a season, choose an easier market first.

Source: [Rainforest Alliance Sustainable Agriculture Standard - Farm Requirements](https://knowledge.rainforest-alliance.org/docs/en/certification-standard-current) · [GLOBALG.A.P.](https://globalgap.org/)', '[{"title":"GLOBALG.A.P.","url":"https://globalgap.org/","publisher":"GLOBALG.A.P."},{"title":"Rainforest Alliance Sustainable Agriculture Standard","url":"https://knowledge.rainforest-alliance.org/docs/en/certification-standard-current","publisher":"Rainforest Alliance"},{"title":"Fairtrade International","url":"https://www.fairtrade.net/us-en.html","publisher":"Fairtrade International"},{"title":"Rainforest Alliance","url":"https://www.rainforest-alliance.org/","publisher":"Rainforest Alliance"}]', 'Compiled from institutional trade guidance', 'GLOBALG.A.P., Rainforest Alliance, Fairtrade International', 1, 2, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_cocoa-export-eudr', 'cocoa-export-eudr', 'Exporting cocoa to the EU under the Deforestation Regulation', 'Cocoa', '18', NULL, 'Cocoa is explicitly covered by the EU Deforestation Regulation. This playbook covers what the regulation requires, when it applies, and what a producer country exporter must be able to prove.', '## Step 1: Know that cocoa is named in the regulation

Regulation (EU) 2023/1115 governs the making available on the Union market and the export from the Union of certain commodities and products associated with deforestation and forest degradation, and repeals the earlier timber regulation. The commodities covered include cattle, cocoa, coffee, palm oil, rubber, soy and wood, plus certain products made from them. If you export cocoa or cocoa products to the EU, this applies to you through your EU buyer.

Source: [Regulation (EU) 2023/1115](https://eur-lex.europa.eu/eli/reg/2023/1115/oj) · [Regulation on deforestation-free products](https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en)

## Step 2: Work to the application date

The European Commission states that from 30 December 2026, products placed on, sold within, or exported from the EU must be free from deforestation. Companies placing these products on the EU market for the first time, or exporting them, must be able to show the products are deforestation free and produced in line with the relevant laws of the country of production. Your buyer will need this from you before that date, not on it.

Source: [Deforestation Regulation implementation](https://green-forum.ec.europa.eu/nature-and-biodiversity/deforestation-regulation-implementation_en)

## Step 3: Understand the two things you must prove

There are two separate tests. First, deforestation free, meaning the cocoa was not grown on land deforested after the cut off. Second, legality, meaning production complied with the relevant laws of the country where it was produced. Certification alone does not automatically satisfy either. You need farm level geolocation data and evidence of legal land tenure and compliance, held in a form your EU buyer can use in their own due diligence.

Source: [Deforestation Regulation implementation](https://green-forum.ec.europa.eu/nature-and-biodiversity/deforestation-regulation-implementation_en) · [Regulation (EU) 2023/1115](https://eur-lex.europa.eu/eli/reg/2023/1115/oj)

## Step 4: Find out your country''s risk classification

An EU Implementing Regulation classifies countries according to their risk of deforestation when producing the covered commodities, with the methodology set out in a Staff Working Document and in the annex of the strategic framework. The classification affects the depth of due diligence your buyer must perform. Check where your country sits, because it changes how much evidence you will be asked for.

Source: [Regulation on deforestation-free products](https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en)

## Step 5: Use the official guidance and the information system

The Commission publishes a guidance document on the EUDR and maintains a dedicated implementation resource hub with practical information for importers, exporters, processors and other supply chain participants, explicitly including non-EU suppliers. There is an EUDR Information System, and an EU observatory publishing maps and datasets on forest cover change. Use these rather than relying on second hand summaries from intermediaries.

Source: [Deforestation Regulation implementation](https://green-forum.ec.europa.eu/nature-and-biodiversity/deforestation-regulation-implementation_en) · [Regulation on deforestation-free products](https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en)

## Step 6: Layer certification on top, not instead

Rainforest Alliance certification is widely requested by cocoa buyers, and its Sustainable Agriculture Standard Farm Requirements are the binding document. Fairtrade certification covers cocoa and is aimed at producer economics. Neither replaces EUDR compliance. Treat certification as commercial positioning and EUDR data as the legal entry ticket.

Source: [Rainforest Alliance Sustainable Agriculture Standard - Farm Requirements](https://knowledge.rainforest-alliance.org/docs/en/certification-standard-current) · [Fairtrade International](https://www.fairtrade.net/us-en.html)

## Step 7: Track the market with intergovernmental data

The International Cocoa Organization is a non-profit intergovernmental organization with a mandate to monitor, analyse and disseminate reliable data on the global cocoa economy, including production and grindings. Note that ICCO has moved comprehensive statistical data and recurring publications, including monthly reports older than six months and the Quarterly Bulletin of Cocoa Statistics, to an annual subscription. Budget for it if you need the underlying numbers rather than press commentary.

Source: [ICCO statistics](https://www.icco.org/statistics/) · [International Cocoa Organization](https://www.icco.org/)', '[{"title":"Regulation (EU) 2023/1115 (EUDR)","url":"https://eur-lex.europa.eu/eli/reg/2023/1115/oj","publisher":"European Union (EUR-Lex)"},{"title":"Regulation on deforestation-free products","url":"https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en","publisher":"European Commission"},{"title":"EUDR implementation hub","url":"https://green-forum.ec.europa.eu/nature-and-biodiversity/deforestation-regulation-implementation_en","publisher":"European Commission"},{"title":"International Cocoa Organization","url":"https://www.icco.org/","publisher":"International Cocoa Organization"},{"title":"Rainforest Alliance Sustainable Agriculture Standard - Farm Requirements","url":"https://knowledge.rainforest-alliance.org/docs/en/certification-standard-current","publisher":"Rainforest Alliance"},{"title":"Fairtrade International","url":"https://www.fairtrade.net/us-en.html","publisher":"Fairtrade International"},{"title":"ICCO statistics","url":"https://www.icco.org/statistics/","publisher":"International Cocoa Organization"}]', 'Compiled from institutional trade guidance', 'European Union (EUR-Lex), European Commission, International Cocoa Organization, Rainforest Alliance, Fairtrade International', 1, 3, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_horticulture-export-eu', 'horticulture-export-eu', 'Exporting fresh produce and horticulture to the EU', 'Agriculture & food', NULL, NULL, 'The specific chain of requirements for fruit, vegetables and cut flowers going into the European market, from farm records to the phytosanitary certificate.', '## Step 1: Build farm records before you build a customer list

Everything downstream depends on being able to say which farm grew which box, what was sprayed on it and when. Without that you cannot pass a residue investigation, you cannot get GLOBALG.A.P. certified, and you cannot answer a buyer audit. Start a simple written spray log and harvest log per plot in your first season. This is the cheapest thing on this list and the one most exporters skip.

Source: [GLOBALG.A.P.](https://globalgap.org/)

## Step 2: Test against EU maximum residue levels

The EU sets maximum residue levels for pesticides in food, and these are revised as scientific opinions come in. Send samples to an accredited laboratory and test against the current EU limits for your crop, using the actual chemicals your growers use. A single grower using an unapproved product can cause the rejection of a whole consolidated consignment, which is why you need per farm traceability first.

Source: [Maximum residue levels](https://food.ec.europa.eu/plants/pesticides/maximum-residue-levels_en)

## Step 3: Get GLOBALG.A.P. certified if you are targeting retail

GLOBALG.A.P. sets standards for primary production and the supply chain from fruits and flowers to fish and feed, using third party certification developed with sector stakeholders. Its coverage includes food safety, environment, worker health and safety and welfare, and supply chain transparency. European supermarkets commonly treat it as a minimum. If you are selling to wholesale markets or processors instead, you may not need it, so confirm with the buyer.

Source: [GLOBALG.A.P.](https://globalgap.org/)

## Step 4: Clear plant health and get the phytosanitary certificate

EU plant health rules are designed to prevent the introduction of quarantine pests into the EU, covering crops, fruits, vegetables, flowers and ornamentals. The EU participates in the International Plant Protection Convention, which sets the international standards behind the phytosanitary certificate. Only your national plant protection organisation can issue the certificate, and inspection has to happen before departure. Book that inspection into your packing schedule, not after it.

Source: [Plant health and biosecurity](https://food.ec.europa.eu/plants/plant-health-and-biosecurity_en) · [International Plant Protection Convention](https://www.ippc.int/en/)

## Step 5: Handle organic claims properly or drop them

For produce from most African countries, marketing as organic in the EU requires certification by a control body or control authority recognised and supervised by the European Commission, and operators are checked at least once a year. There is no informal route. If you cannot fund annual inspection, sell conventional and compete on quality and reliability instead.

Source: [Trade in organic products](https://agriculture.ec.europa.eu/farming/organic-farming/trade_en) · [Organic farming at a glance](https://agriculture.ec.europa.eu/farming/organic-farming/organics-glance_en)

## Step 6: Price the cold chain into your Incoterm

Fresh produce fails commercially through temperature breaks and delays far more often than through paperwork. Decide where your responsibility ends using an Incoterms 2020 rule with a named place, and make sure that point matches where you actually stop controlling the temperature. Do not accept a delivered term if you cannot control the cold chain to that destination.

Source: [Incoterms 2020](https://iccwbo.org/business-solutions/incoterms-rules/incoterms-2020/)', '[{"title":"GLOBALG.A.P.","url":"https://globalgap.org/","publisher":"GLOBALG.A.P."},{"title":"EU maximum residue levels","url":"https://food.ec.europa.eu/plants/pesticides/maximum-residue-levels_en","publisher":"European Commission"},{"title":"EU plant health and biosecurity","url":"https://food.ec.europa.eu/plants/plant-health-and-biosecurity_en","publisher":"European Commission"},{"title":"International Plant Protection Convention","url":"https://www.ippc.int/en/","publisher":"IPPC Secretariat, FAO"},{"title":"Trade in organic products","url":"https://agriculture.ec.europa.eu/farming/organic-farming/trade_en","publisher":"European Commission"},{"title":"Organic farming at a glance","url":"https://agriculture.ec.europa.eu/farming/organic-farming/organics-glance_en","publisher":"European Commission"},{"title":"Incoterms 2020","url":"https://iccwbo.org/business-solutions/incoterms-rules/incoterms-2020/","publisher":"International Chamber of Commerce"}]', 'Compiled from institutional trade guidance', 'GLOBALG.A.P., European Commission, IPPC Secretariat, FAO, International Chamber of Commerce', 1, 2, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_afcfta-how-to-use-it', 'afcfta-how-to-use-it', 'Using the AfCFTA: rules of origin, certificates and the Guided Trade Initiative', NULL, NULL, NULL, 'How an African business actually claims preferential treatment under the African Continental Free Trade Area, rather than just reading about it.', '## Step 1: Know what the agreement is

The AfCFTA is one of the flagship projects of Agenda 2063 and is a high ambition trade agreement with a comprehensive scope. The AfCFTA Secretariat is the institutional home for its operational instruments. Preferential treatment is not automatic. You have to claim it, and to claim it you must satisfy the rules of origin and present the right certificate.

Source: [AfCFTA](https://au-afcfta.org/)

## Step 2: Check your product against the rules of origin

The AfCFTA Rules of Origin Manual is the guide to operationalising Annex 2 on Rules of Origin. Rules of origin determine whether a good counts as originating in an AfCFTA state party and therefore qualifies for preferential tariff treatment. Products with a lot of imported input often fail. Check your specific product''s rule before you promise a buyer a duty free price, because you may be assembling from non-originating materials without realising it.

Source: [AfCFTA Rules of Origin](https://au-afcfta.org/rules-of-origin/)

## Step 3: Use the Rules of Origin Facilitator to check before you commit

ITC runs a Rules of Origin Facilitator and its Market Access Map offers a list of trade agreements with their corresponding texts of rules of origin and certificates of origin. Run your HS code and your intended trade route through it and read the actual origin criterion. This takes an afternoon and prevents an expensive misquote.

Source: [Rules of Origin Facilitator](https://findrulesoforigin.org/) · [ITC Market Access Map](https://www.intracen.org/resources/tools/market-access-map)

## Step 4: Get the certificate of origin from the designated authority

The certificate of origin is what proves your claim to the customs authority in the importing state party. It is issued by the competent authority designated in your country, not by you or your buyer. Contact your national trade or customs authority to find out which body issues AfCFTA certificates and what evidence they require, and do this before your first order, because approval and registration take time.

Source: [AfCFTA Rules of Origin](https://au-afcfta.org/rules-of-origin/) · [ITC Market Access Map](https://www.intracen.org/resources/tools/market-access-map)

## Step 5: Look at the Guided Trade Initiative

The AfCFTA Guided Trade Initiative was launched on 7 October 2022 as a strategic approach to initiate commercially meaningful trade under the agreement. It is the practical proving ground where participating countries and selected products actually move under AfCFTA preferences. If your product and country are in scope, this is a concrete route in rather than a general aspiration. Check the current participating countries and product lists with the Secretariat.

Source: [AfCFTA Guided Trade Initiative](https://au-afcfta.org/guided-trade-initiative/)

## Step 6: Use the regional analytical support

The African Trade Policy Centre, established in June 2003 and based at UN Economic Commission for Africa headquarters in Addis Ababa, works to strengthen African governments'' capacity to formulate and implement trade policy, with explicit involvement of the private sector in research, training, information dissemination and advisory services. Its analysis of export diversification obstacles is useful background when you are deciding which African market to enter first.

Source: [African Trade Policy Centre](https://www.uneca.org/african-trade-policy-centre) · [UNECA](https://www.uneca.org/)', '[{"title":"AfCFTA Secretariat","url":"https://au-afcfta.org/","publisher":"AfCFTA Secretariat"},{"title":"AfCFTA Rules of Origin","url":"https://au-afcfta.org/rules-of-origin/","publisher":"AfCFTA Secretariat"},{"title":"AfCFTA Guided Trade Initiative","url":"https://au-afcfta.org/guided-trade-initiative/","publisher":"AfCFTA Secretariat"},{"title":"African Trade Policy Centre","url":"https://www.uneca.org/african-trade-policy-centre","publisher":"United Nations Economic Commission for Africa"},{"title":"Rules of Origin Facilitator","url":"https://findrulesoforigin.org/","publisher":"International Trade Centre"},{"title":"ITC Market Access Map","url":"https://www.intracen.org/resources/tools/market-access-map","publisher":"International Trade Centre"},{"title":"UNECA","url":"https://www.uneca.org/","publisher":"United Nations Economic Commission for Africa"}]', 'Compiled from institutional trade guidance', 'AfCFTA Secretariat, United Nations Economic Commission for Africa, International Trade Centre', 1, 2, datetime('now'), datetime('now'));
INSERT INTO playbooks (id, slug, title, sector, hs_code, country_iso3, summary, body_md, sources, author_name, author_credential, premium_only, reading_minutes, published_at, updated_at) VALUES ('pb_national-export-agencies-africa', 'national-export-agencies-africa', 'Your national export promotion agency and what it does for you', NULL, NULL, NULL, 'The government body in each country that exists specifically to help exporters, what registering with it gets you, and how to use it instead of paying a broker.', '## Step 1: Register with the national body first

Almost every country channels its export support through one agency, and access to that support usually requires registration. The Nigerian Export Promotion Council frames its services as being for registered Nigerian exporters. Registration is normally the gateway to training, market information, trade fair participation and, in some countries, the export documentation you need to move goods legally. Do it before you look for buyers.

Source: [NEPC services](https://nepc.gov.ng/about-us/services/) · [Nigerian Export Promotion Council](https://nepc.gov.ng/)

## Step 2: Ghana: Ghana Export Promotion Authority

GEPA is Ghana''s national export promotion body and publishes ongoing guidance for Ghanaian exporters, including on the handling of export proceeds. Contact them for the current exporter registration requirements and for sector specific support programmes. Use the official site rather than intermediaries, since several unofficial sites carry outdated procedures.

Source: [Ghana Export Promotion Authority](https://www.gepaghana.org/)

## Step 3: Nigeria: Nigerian Export Promotion Council

NEPC operates a network of local offices across Nigerian states, including Lokoja, Sokoto, Calabar, Asaba, Osogbo, Bauchi, Katsina, Makurdi, Maiduguri, Ilorin, Gusau, Benin, Abakaliki, Abeokuta and Akure, described as smart offices with staff available to assist. If you are outside Lagos or Abuja, find your nearest office and go in person. Its services page is organised as an overview of individual services for registered exporters.

Source: [Nigerian Export Promotion Council](https://nepc.gov.ng/) · [NEPC services](https://nepc.gov.ng/about-us/services/)

## Step 4: Kenya: use the electronic single window

The Kenya Trade Network Agency, KenTrade, is a state agency under the National Treasury mandated to facilitate cross border trade and to establish, manage and implement the National Electronic Single Window System. For a Kenyan exporter, this is where the permits and declarations from multiple agencies are handled in one place. Register on the single window early, since account setup is a prerequisite to filing anything.

Source: [Kenya Trade Network Agency](https://kentrade.go.ke/)

## Step 5: South Africa: the dtic funds market entry directly

South Africa''s Department of Trade, Industry and Competition runs open calls for funding to participate in international trade exhibitions. As a current example, it invited agro-processing companies to apply for funding to attend Gulfood 2027 in Dubai from 15 to 19 March 2027, with applications closing 15 October 2026, in a fine food pavilion excluding meat, confectionery and beverages. Watch the dtic site for these calls, because the deadlines are real and the money is finite.

Source: [the dtic](https://www.thedtic.gov.za/)

## Step 6: Combine the national agency with the free international tools

Your national agency knows the local procedure. It will rarely have granular data on foreign demand. Pair it with ITC Trade Map for import demand, Market Access Map for tariffs and requirements, and the Global Trade Helpdesk for consolidated market information. Bring specific data to your agency meeting and you will get a far more useful conversation than if you arrive asking where to sell.

Source: [ITC Trade Map](https://www.intracen.org/resources/tools/trade-map) · [Global Trade Helpdesk](https://globaltradehelpdesk.org/en) · [ITC SME Trade Academy](https://www.intracen.org/resources/tools/sme-trade-academy)', '[{"title":"NEPC services","url":"https://nepc.gov.ng/about-us/services/","publisher":"Nigerian Export Promotion Council"},{"title":"Nigerian Export Promotion Council","url":"https://nepc.gov.ng/","publisher":"Nigerian Export Promotion Council"},{"title":"Ghana Export Promotion Authority","url":"https://www.gepaghana.org/","publisher":"Ghana Export Promotion Authority"},{"title":"Kenya Trade Network Agency","url":"https://kentrade.go.ke/","publisher":"Kenya Trade Network Agency"},{"title":"the dtic","url":"https://www.thedtic.gov.za/","publisher":"Department of Trade, Industry and Competition, South Africa"},{"title":"ITC Trade Map","url":"https://www.intracen.org/resources/tools/trade-map","publisher":"International Trade Centre"},{"title":"Global Trade Helpdesk","url":"https://globaltradehelpdesk.org/en","publisher":"International Trade Centre / WTO / UNCTAD"},{"title":"ITC SME Trade Academy","url":"https://www.intracen.org/resources/tools/sme-trade-academy","publisher":"International Trade Centre"}]', 'Compiled from institutional trade guidance', 'Nigerian Export Promotion Council, Ghana Export Promotion Authority, Kenya Trade Network Agency, Department of Trade, Industry and Competition, South Africa, International Trade Centre, International Trade Centre / WTO / UNCTAD', 1, 2, datetime('now'), datetime('now'));
