import { readFileSync, writeFileSync, existsSync } from 'node:fs';

// Source JSON lives in the repo so the seed can be rebuilt or amended without
// re-running the research pass that produced it.
const RESEARCH_DIR = 'data/research';

const INPUTS = [
  'seed-orgs.json',
  'seed-africa-oceania.json',
  'seed-asia-europe.json',
  'seed-americas.json',
];

const OUT = 'data/seed.sql';

/**
 * Countries ticked on out of the box so the dashboard has something in it.
 * Everything else ships inactive — the admin decides.
 */
const DEFAULT_ACTIVE = new Set([
  'ghana',
  'nigeria',
  'south-africa',
  'kenya',
  'cote-divoire',
  'united-states',
  'china',
  'germany',
]);

const VALID_KINDS = new Set(['country', 'intl_org', 'regional_body']);
const VALID_CATS = ['export', 'import', 'commerce'];
const VALID_FMTS = new Set(['html', 'csv', 'json', 'api', 'sdmx', 'xlsx', 'pdf']);
const VALID_CONTINENTS = new Set([
  'Africa',
  'Asia',
  'Europe',
  'North America',
  'South America',
  'Oceania',
  'Global',
]);

const q = (v) => (v == null || v === '' ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);

function slugify(s) {
  return String(s)
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

const entities = [];
const bySlug = new Map();
const warnings = [];

for (const file of INPUTS) {
  const path = `${RESEARCH_DIR}/${file}`;
  if (!existsSync(path)) {
    warnings.push(`missing input: ${file}`);
    continue;
  }
  const arr = JSON.parse(readFileSync(path, 'utf8'));
  for (const raw of arr) {
    if (!raw?.name || !VALID_KINDS.has(raw.kind)) {
      warnings.push(`dropped malformed record in ${file}: ${JSON.stringify(raw).slice(0, 90)}`);
      continue;
    }
    const slug = slugify(raw.slug || raw.name);
    if (bySlug.has(slug)) {
      // Merge extra links into the record we already have rather than losing them.
      const existing = bySlug.get(slug);
      for (const cat of VALID_CATS) {
        const incoming = raw.sources?.[cat] ?? [];
        for (const s of incoming) {
          if (existing.sources[cat].length < 3 && !existing.sources[cat].some((x) => x.url === s.url))
            existing.sources[cat].push(s);
        }
      }
      warnings.push(`merged duplicate slug: ${slug}`);
      continue;
    }

    const continent = VALID_CONTINENTS.has(raw.continent)
      ? raw.continent
      : raw.kind === 'country'
        ? null
        : 'Global';
    if (raw.continent && !VALID_CONTINENTS.has(raw.continent))
      warnings.push(`unknown continent "${raw.continent}" on ${slug}`);

    const iso3 =
      typeof raw.iso3 === 'string' && /^[A-Za-z]{3}$/.test(raw.iso3)
        ? raw.iso3.toUpperCase()
        : null;
    if (raw.kind === 'country' && !iso3) warnings.push(`country without iso3: ${slug}`);

    const sources = { export: [], import: [], commerce: [] };
    for (const cat of VALID_CATS) {
      const list = Array.isArray(raw.sources?.[cat]) ? raw.sources[cat] : [];
      for (const s of list.slice(0, 3)) {
        if (!s?.url || !/^https?:\/\//i.test(s.url)) {
          warnings.push(`bad url dropped on ${slug}/${cat}: ${s?.url}`);
          continue;
        }
        sources[cat].push({
          url: s.url.trim(),
          label: s.label ?? null,
          fmt: VALID_FMTS.has(s.fmt) ? s.fmt : 'html',
          endpoint_type: s.endpoint_type ?? 'file',
          parser_key: s.parser_key ?? 'auto',
          config_json: typeof s.config_json === 'string' ? s.config_json : JSON.stringify(s.config ?? {}),
          tls: s.tls_warning ? 1 : 0,
        });
      }
    }

    const record = {
      id: `ent_${slug}`.slice(0, 40),
      slug,
      name: raw.name.trim(),
      kind: raw.kind,
      continent,
      iso3,
      agency_name: raw.agency_name ?? null,
      homepage: raw.homepage ?? null,
      api_notes: raw.api_notes ?? null,
      is_active: DEFAULT_ACTIVE.has(slug) ? 1 : 0,
      sources,
    };
    entities.push(record);
    bySlug.set(slug, record);
  }
}

const lines = [
  '-- Tereflow seed data',
  '-- Generated by scripts/build-seed.mjs from verified research output.',
  '-- Every URL below was HTTP-checked at research time; the weekly cron re-checks them.',
  '',
  'DELETE FROM entity_sources;',
  'DELETE FROM entities;',
  '',
];

for (const e of entities) {
  lines.push(
    `INSERT INTO entities (id, slug, name, kind, continent, iso3, agency_name, homepage, api_notes, is_active) VALUES (` +
      [
        q(e.id),
        q(e.slug),
        q(e.name),
        q(e.kind),
        q(e.continent),
        q(e.iso3),
        q(e.agency_name),
        q(e.homepage),
        q(e.api_notes),
        e.is_active,
      ].join(', ') +
      ');',
  );
  for (const cat of VALID_CATS) {
    e.sources[cat].forEach((s, i) => {
      lines.push(
        `INSERT INTO entity_sources (id, entity_id, category, slot, url, label, fmt, endpoint_type, parser_key, config_json, tls_warning) VALUES (` +
          [
            q(`src_${e.slug}_${cat}_${i + 1}`.slice(0, 60)),
            q(e.id),
            q(cat),
            i + 1,
            q(s.url),
            q(s.label),
            q(s.fmt),
            q(s.endpoint_type),
            q(s.parser_key),
            q(s.config_json),
            s.tls,
          ].join(', ') +
          ');',
      );
    });
  }
}

writeFileSync(OUT, lines.join('\n') + '\n', 'utf8');

const counts = entities.reduce((a, e) => ((a[e.kind] = (a[e.kind] || 0) + 1), a), {});
const linkCount = entities.reduce(
  (a, e) => a + VALID_CATS.reduce((b, c) => b + e.sources[c].length, 0),
  0,
);
const byContinent = entities
  .filter((e) => e.kind === 'country')
  .reduce((a, e) => ((a[e.continent ?? '??'] = (a[e.continent ?? '??'] || 0) + 1), a), {});

console.log(`Wrote ${OUT}`);
console.log(`Entities: ${entities.length} ${JSON.stringify(counts)}`);
console.log(`Countries by continent: ${JSON.stringify(byContinent)}`);
console.log(`Source links: ${linkCount}`);
console.log(`Active by default: ${entities.filter((e) => e.is_active).map((e) => e.slug).join(', ')}`);
console.log(`Ghana present: ${bySlug.has('ghana')}`);
if (warnings.length) {
  console.log(`\nWarnings (${warnings.length}):`);
  for (const w of warnings.slice(0, 40)) console.log(`  - ${w}`);
}
