/**
 * Export the analysed database records to restorable SQL parts.
 *
 * The registry (entities, sources, playbooks) is seeded from data/seed.sql and
 * data/playbooks.sql, which are authored. This covers the other half: the
 * numbers the weekly agent produced from UN Comtrade and the World Bank, plus
 * everything derived from them.
 *
 * Why keep it at all, when the agent regenerates it every Friday: a fresh clone
 * would otherwise show empty dashboards until someone runs the agent and waits
 * on rate-limited public APIs. Without a Comtrade key that first run is slow.
 * It is also a point-in-time record of what the sources actually said, which
 * matters when a figure is later revised.
 *
 * Personal data is deliberately excluded. Users, cards, messages, ratings,
 * sessions, subscriptions, feed items and billing events are never exported.
 *
 *   node scripts/export-data.mjs      writes data/snapshot/*.sql
 *   npm run data:restore              applies them in order
 */
import { DatabaseSync } from 'node:sqlite';
import { writeFileSync, mkdirSync, readdirSync, statSync, rmSync } from 'node:fs';
import { join } from 'node:path';

const OUT_DIR = 'data/snapshot';
const D1_DIR = '.wrangler/state/v3/d1/miniflare-D1DatabaseObject';

/**
 * Cap on each generated file.
 *
 * `wrangler d1 execute --file` streams the whole file in one request and dies
 * with an undici "Body Timeout Error" on anything large: a single 2.94MB file
 * timed out after five minutes. Parts of a few hundred KB apply comfortably.
 */
const MAX_FILE = 350 * 1024;

/** Cap on a single INSERT. Rows carrying JSON payloads blow past this fast. */
const MAX_STATEMENT = 16 * 1024;

// Ordered so foreign keys resolve on restore.
const TABLES = ['analysis_runs', 'trade_facts', 'analysis_results', 'opportunity_signals'];

/** Miniflare names the file after an internal id, so take the largest .sqlite. */
function findDb() {
  const files = readdirSync(D1_DIR)
    .filter((f) => f.endsWith('.sqlite'))
    .map((f) => ({ path: join(D1_DIR, f), size: statSync(join(D1_DIR, f)).size }))
    .sort((a, b) => b.size - a.size);
  if (files.length === 0) {
    throw new Error(`No local D1 database under ${D1_DIR}. Run the migrations first.`);
  }
  return files[0].path;
}

const lit = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'bigint') return String(v);
  if (typeof v === 'boolean') return v ? 1 : 0;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const HEADER =
  '-- Tereflow analysed-data snapshot\n' +
  '-- Generated by scripts/export-data.mjs. Do not edit by hand.\n' +
  '-- Contains no personal data.\n\n';

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const db = new DatabaseSync(findDb(), { readOnly: true });

let part = 0;
const written = [];
const summary = [];
let buffer = '';

function writePart() {
  if (!buffer.trim()) return;
  part++;
  const name = `${String(part).padStart(2, '0')}.sql`;
  const body = HEADER + buffer;
  writeFileSync(join(OUT_DIR, name), body, 'utf8');
  written.push({ name, bytes: Buffer.byteLength(body) });
  buffer = '';
}

function push(line) {
  if (buffer.length > 0 && Buffer.byteLength(buffer) + line.length > MAX_FILE) writePart();
  buffer += line + '\n';
}

for (const table of TABLES) {
  const rows = db.prepare(`SELECT * FROM ${table}`).all();
  summary.push(`${table}: ${rows.length}`);
  push(`DELETE FROM ${table};`);
  if (rows.length === 0) continue;

  const cols = Object.keys(rows[0]);
  const prefix = `INSERT INTO ${table} (${cols.join(', ')}) VALUES `;
  let batch = [];
  let size = prefix.length;

  const flush = () => {
    if (batch.length === 0) return;
    push(prefix + batch.join(',') + ';');
    batch = [];
    size = prefix.length;
  };

  for (const r of rows) {
    const tuple = `(${cols.map((c) => lit(r[c])).join(',')})`;
    if (batch.length > 0 && size + tuple.length + 1 > MAX_STATEMENT) flush();
    batch.push(tuple);
    size += tuple.length + 1;
  }
  flush();
}

writePart();
db.close();

const total = written.reduce((a, f) => a + f.bytes, 0);
console.log(`Wrote ${written.length} part(s) to ${OUT_DIR}/  (${(total / 1024 / 1024).toFixed(2)} MB)`);
for (const s of summary) console.log('  ' + s);
console.log(`  largest part: ${(Math.max(...written.map((f) => f.bytes)) / 1024).toFixed(0)} KB`);
